services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000" # Expose Chroma DB API on port 8000
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    volumes:
      - chroma_data:/data # Persist Chroma DB data

volumes:
  chroma_data:
    driver: local
